-- MySQL Script generated by MySQL Workbench
-- 01/22/16 15:49:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema sdd-ufg
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`processes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`processes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `initial_date` DATE NOT NULL,
  `teacher_intent_date` VARCHAR(45) NULL,
  `primary_distribution_date` VARCHAR(45) NULL,
  `substitute_intent_date` VARCHAR(45) NULL,
  `secondary_distribution_date` VARCHAR(45) NULL,
  `final_date` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`process_configurations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`process_configurations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `data_type` VARCHAR(45) NOT NULL,
  `type` ENUM('CRITERIA', 'RESTRICTION') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`restricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`restricao` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`processes_process_configurations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`processes_process_configurations` (
  `process_id` INT NOT NULL,
  `process_configuration_id` INT NOT NULL,
  PRIMARY KEY (`process_id`, `process_configuration_id`),
  INDEX `fk_processo_distribuicao_has_criterio_criterio_idx` (`process_configuration_id` ASC),
  CONSTRAINT `fk_processo_distribuicao_has_criterio_criterio`
    FOREIGN KEY (`process_configuration_id`)
    REFERENCES `mydb`.`process_configurations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_processo_distribuicao_has_criterio_processo_distribuicao1`
    FOREIGN KEY (`process_id`)
    REFERENCES `mydb`.`processes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`teachers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `registry` VARCHAR(45) NOT NULL,
  `url_lattes` VARCHAR(128) NULL,
  `entry_date` DATE NOT NULL,
  `formation` VARCHAR(45) NULL,
  `workload` INT NOT NULL,
  `about` VARCHAR(255) NULL,
  `rg` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `birth_date` DATE NOT NULL,
  `situation` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`knowledges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`knowledges` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`schedules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `initial_time` TIME(1) NOT NULL,
  `final_time` TIME(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subjects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `teoric_workload` INT NOT NULL,
  `practical_workload` INT NOT NULL,
  `knowledge_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_disciplina_nucleo_conhecimento1_idx` (`knowledge_id` ASC),
  INDEX `fk_subjects_courses1_idx` (`course_id` ASC),
  CONSTRAINT `fk_disciplina_nucleo_conhecimento1`
    FOREIGN KEY (`knowledge_id`)
    REFERENCES `mydb`.`knowledges` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subjects_courses1`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`locals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`locals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `capacity` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clazzes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clazzes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `vacancies` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `schedule_id` INT NOT NULL,
  `local_id` INT NOT NULL,
  `process_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_turma_disciplina1_idx` (`subject_id` ASC),
  INDEX `fk_turma_horario1_idx` (`schedule_id` ASC),
  INDEX `fk_turma_local1_idx` (`local_id` ASC),
  INDEX `fk_turma_processo_distribuicao1_idx` (`process_id` ASC),
  CONSTRAINT `fk_turma_disciplina1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `mydb`.`subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_horario1`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `mydb`.`schedules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_local1`
    FOREIGN KEY (`local_id`)
    REFERENCES `mydb`.`locals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_processo_distribuicao1`
    FOREIGN KEY (`process_id`)
    REFERENCES `mydb`.`processes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`knowledges_teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`knowledges_teachers` (
  `teacher_id` INT NOT NULL,
  `knowledge_id` INT NOT NULL,
  `level` TINYINT NOT NULL,
  PRIMARY KEY (`teacher_id`, `knowledge_id`),
  INDEX `fk_docente_has_nucleo_conhecimento_nucleo_conhecimento1_idx` (`knowledge_id` ASC),
  CONSTRAINT `fk_docente_has_nucleo_conhecimento_docente1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `mydb`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_docente_has_nucleo_conhecimento_nucleo_conhecimento1`
    FOREIGN KEY (`knowledge_id`)
    REFERENCES `mydb`.`knowledges` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clazzes_teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clazzes_teachers` (
  `clazz_id` INT NOT NULL,
  `teacher_id` INT NOT NULL,
  `status` ENUM('APPROVED', 'NOT APPROVED') NULL,
  PRIMARY KEY (`clazz_id`, `teacher_id`),
  INDEX `fk_clazzes_teachers_docente1_idx` (`teacher_id` ASC),
  CONSTRAINT `fk_clazzes_teachers_turma1`
    FOREIGN KEY (`clazz_id`)
    REFERENCES `mydb`.`clazzes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clazzes_teachers_docente1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `mydb`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` ENUM('COORDENADOR', 'FACILITADOR') NOT NULL,
  `teacher_id` INT NOT NULL,
  `knowledge_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_roles_teachers1_idx` (`teacher_id` ASC),
  INDEX `fk_roles_knowledges1_idx` (`knowledge_id` ASC),
  CONSTRAINT `fk_roles_teachers1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `mydb`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roles_knowledges1`
    FOREIGN KEY (`knowledge_id`)
    REFERENCES `mydb`.`knowledges` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teachers_change_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`teachers_change_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `modification_date` DATETIME NULL,
  `name` VARCHAR(45) NOT NULL,
  `registry` VARCHAR(45) NOT NULL,
  `url_lattes` VARCHAR(128) NULL,
  `entry_date` DATE NOT NULL,
  `formation` VARCHAR(45) NULL,
  `workload` INT NOT NULL,
  `about` VARCHAR(255) NULL,
  `rg` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `birth_date` DATE NOT NULL,
  `situation` VARCHAR(45) NOT NULL,
  `teacher_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_teachers_change_history_teachers1_idx` (`teacher_id` ASC),
  CONSTRAINT `fk_teachers_change_history_teachers1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `mydb`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `id_admin` TINYINT(1) NOT NULL DEFAULT 0,
  `teacher_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_teachers1_idx` (`teacher_id` ASC),
  CONSTRAINT `fk_users_teachers1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `mydb`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
